version: '3'

services:
  iroha-node0:
    build:
        context: docker
        dockerfile: iroha_node.Dockerfile
    container_name: iroha-node0
    ports:
      - "50051:50051"
      # - "20000:20000"
      - "10001:10001"
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=iroha
      - IROHA_POSTGRES_HOST=localhost
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=iroha
      - CCACHE_DIR=/tmp/ccache
      - KEY=node0
    command: ["bash" , "-c", "sleep 1 && irohad --genesis_block /opt/iroha/genesis.block --config nodes/node0/config.sample --keypair_name nodes/node0/node0"]
    tty: true
    volumes:
        - .:/opt/iroha
        - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node1:
    build:
        context: docker
        dockerfile: iroha_node.Dockerfile
    container_name: iroha-node1
    ports:
      - "50052:50051"
      - "20001:20000"
      - "10002:10001"
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=iroha
      - IROHA_POSTGRES_HOST=localhost
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=iroha
      - KEY=node1
      - CCACHE_DIR=/tmp/ccache
    command: ["bash" , "-c", "sleep 4 && irohad --genesis_block /opt/iroha/genesis.block --config nodes/node1/config.sample --keypair_name nodes/node1/node1"]
    tty: true
    volumes:
      - .:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node2:
    build:
        context: docker
        dockerfile: iroha_node.Dockerfile
    container_name: iroha-node2
    ports:
      - "50053:50051"
      - "20002:20000"
      - "10003:10001"
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=iroha
      - IROHA_POSTGRES_HOST=localhost
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=iroha
      - KEY=node2
      - CCACHE_DIR=/tmp/ccache
    command: ["bash" , "-c", "sleep 7 && irohad --genesis_block /opt/iroha/genesis.block --config nodes/node2/config.sample --keypair_name nodes/node2/node2"]
    tty: true
    volumes:
      - .:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node3:
    build:
        context: docker
        dockerfile: iroha_node.Dockerfile
    container_name: iroha-node3
    ports:
      - "50054:50051"
      - "20003:20000"
      - "10004:10001"
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=iroha
      - IROHA_POSTGRES_HOST=localhost
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=iroha
      - KEY=node3
      - CCACHE_DIR=/tmp/ccache
    command: ["bash" , "-c", "sleep 10 && irohad --genesis_block /opt/iroha/genesis.block --config nodes/node3/config.sample --keypair_name nodes/node3/node3"]
    tty: true
    volumes:
      - .:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

volumes:
  ccache-data:
